apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: syncflow-prod
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: syncflow
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
  - target:
      kind: HPA
      name: syncflow
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
