package com.syncflow.api.agent.ai.domain;

public enum AgentCapability {
    PIPELINE_DESIGN, SCHEMA_MAPPING, CONNECTOR_SELECTION, PERFORMANCE_OPTIMIZATION, ROOT_CAUSE_ANALYSIS, DOCUMENTATION, OPERATIONS_ASSIST, KNOWLEDGE_RETRIEVAL, SECURITY_ADVISOR
}
