apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: syncflow-ap-southeast
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: syncflow
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: REGION, value: "ap-southeast-1" }
      - op: replace
        path: /spec/replicas
        value: 2
