apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: syncflow-db
  namespace: syncflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: syncflow-db
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: /syncflow/database
        property: url
    - secretKey: username
      remoteRef:
        key: /syncflow/database
        property: username
    - secretKey: password
      remoteRef:
        key: /syncflow/database
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: syncflow-encryption
  namespace: syncflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: syncflow-encryption
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: /syncflow/encryption
        property: key
