apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: syncflow
  namespace: syncflow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: syncflow
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 5432
        - port: 443
        - port: 80
