apiVersion: v1
kind: Service
metadata:
  name: syncflow
  namespace: syncflow
  labels:
    app.kubernetes.io/name: syncflow
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: syncflow
